name: tf-setup

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    #workflow_dispatch:

env:
    ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
    ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
    ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
    ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}

jobs:
    Terraform-installion:
        runs-on: ubuntu-latest
        steps:
            #- uses: actions/checkout@v2
            - name: install-tfenv
              run: git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv

            - name: make-tfenv-folder
              run: mkdir -p ~/.local/bin/                           

            - name: soft-linking
              run: ln -s ~/.tfenv/bin/* ~/.local/bin    
            
            - name: install-terraform
              run: tfenv install 1.9.5

            - name: set-terraform-version
              run: tfenv use 1.9.5

            - name: checkout-tf-plans
              uses: actions/checkout@v2

            - name: list-files
              run: ls
            
            - name: tf-init
              run: terraform init

            - name: tf-plan
              run: terraform plan

            - name: tf-apply
              run: terraform apply -auto-approve
    