name: tf-setup

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    #workflow_dispatch:

jobs:
    Terraform-installion:
        runs-on: ubuntu-latest
        steps:
            #- uses: actions/checkout@v2
            - name: install-tfenv
              run: git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv

            - name: mkdir
              run: mkdir -p ~/.local/bin/                           

            - name: lnss
              run: ln -s ~/.tfenv/bin/* ~/.local/bin    
            
            - name: install terraform
              run: tfenv install 1.9.5

            - name: install terraform
              run: tfenv use 1.9.5

            - name: check terraform
              run: echo `terraform --version`
            
