name: tf-setup

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    #workflow_dispatch:

jobs:
    tfenv-install:
        runs-on: ubuntu-latest
        steps:
            #- uses: actions/checkout@v2
            - name: install-tfenv
              run: git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv

            - name: mkdir
              run: mkdir -p ~/.local/bin/              
              #. ~/.profile

            - name: lnss
              run: ln -s ~/.tfenv/bin/* ~/.local/bin

            - name: whichtf
              run: which tfenv

            - name:
              run: echo $PWD
            #  shell: bash
